### ISSUE TITLE
what ？很多都是重复的？

### ISSUE THREAD

**Issue by wwwang89** [liberalisman/iOS-InterviewQuestion-collection#15]
性能优化章节里面，很多都是一样的，随便举个例子：

https://github.com/liberalisman/iOS-InterviewQuestion-collection/blob/master/性能优化/20.第二十题.md
https://github.com/liberalisman/iOS-InterviewQuestion-collection/blob/master/性能优化/14.第十四题.md

**Comment by liberalisman** [comment]
没有写链接的都是留着待补充，而之所以你在源文件发现相同的内容，是我一开始就复制过去的，，所以这些你根本不用看

**Comment by SilenceZhou** [comment]
混淆视听有点不是很友好，推荐把不必要的删除吧
