### ISSUE TITLE
太多的冗余文件希望删掉吧

### ISSUE THREAD

**Issue by SilenceZhou** [liberalisman/iOS-InterviewQuestion-collection#17]
分类和类拓展的区别?
1.分类 的加载在 运行时，类拓展 的加载在 编译时。

2.分类 不能给系统的类添加方法。

3.类拓展 只以声明的形式存在，一般存在 .m 文件中。

**Comment by liberalisman** [comment]
解释一下，当时我在初始化时，考虑了很多模块，所以采用复制的方式，创建了很多预留的文件。而最近半年很忙，就没有顾得上去补全，后期有时间的话，我还是会完善的
