### ISSUE TITLE
ARC 的 retainCount 怎么存储的？

### ISSUE THREAD

**Issue by Leungwn** [liberalisman/iOS-InterviewQuestion-collection#3]
ARC 的 retainCount 怎么存储的？ 
这个问题不甚了解 有解析下吗？感谢

**Comment by liberalisman** [comment]
你好，具体的实现细节和技术方案，可以参考如下文章：http://yulingtianxia.com/blog/2015/12/06/The-Principle-of-Refenrence-Counting/。

**Comment by Leungwn** [comment]
OK，感谢
