### ISSUE TITLE
计算题/1.第一题.md 文件一片空白

### ISSUE THREAD

**Issue by FlyKite** [liberalisman/iOS-InterviewQuestion-collection#6]
另外，提个小建议，文件名前缀改成01 02 03这样的话会更方便顺序排列（不过似乎顺序并不影响）

**Comment by FlyKite** [comment]
“代码管理”目录下的“12.第十二题.md”到“3.3-6.md”这些文件内容重复，都是“分类和类拓展的区别?”

**Comment by liberalisman** [comment]
你好，因为在建目录的时候，我需要创建大量的文件，所以很多文件都是拷贝的同一份。
目前写了思路的在 README.MD 中都是有链接的，没有链接的是暂时还没有写，最近比较忙。

**Comment by liberalisman** [comment]
计算题的第一题已经直接给你答案了
