### ISSUE TITLE
这里还有一些问题，推荐一起整理。

### ISSUE THREAD

**Issue by mrmign** [liberalisman/iOS-InterviewQuestion-collection#7]
https://medium.com/seyhunakyurek/interview-guideline-for-senior-lead-ios-developers-997484ed53da?ct=t(EMAIL_CAMPAIGN_6_11_2018_18_51)&mc_cid=32ae21522a&mc_eid=bd61a9a59c

**Comment by liberalisman** [comment]
非常感谢你的关注和建议，最近忙的不行，有时间我一定加上
